<?php

$config['system'] = [
    'httpcodes' => array(
        '100' => ['Continuar', 'O solicitante deve continuar com a solicitação'],
        '101' => ['Mudando protocolos', 'O solicitante pediu ao servidor para mudar os protocolos e o servidor está reconhecendo a informação para, então, executá-la'],
        '200' => ['Bem-sucedido', 'O servidor processou a solicitação'],
        '201' => ['Criado', 'A solicitação foi bem-sucedida e o servidor criou um novo recurso'],
        '202' => ['Aceito', 'O servidor aceitou a solicitação, mas ainda não a processou'],
        '203' => ['Informação não autorizável', '	O servidor processou a solicitação com sucesso, mas está retornando informações que podem ser de outra fonte'],
        '204' => ['Sem conteúdo', 'O servidor processou a solicitação com sucesso, mas não está retornando nenhum conteúdo'],
        '205' => ['Reconfigurar conteúdo', 'O servidor processou a solicitação com sucesso, mas não está retornando nenhum conteúdo'],
        '206' => ['Conteúdo parcial', 'O servidor processou uma solicitação parcial GET com sucesso'],
        '300' => ['Múltipla escolha', 'O servidor tem várias ações disponíveis com base na solicitação'],
        '301' => ['Movido permanentemente', 'A página solicitada foi movida permanentemente para um novo local'],
        '302' => ['Movido temporariamente', 'O servidor está respondendo à solicitação de uma página de uma localidade diferente, mas o solicitante deve continuar a usar o local original para solicitações futuras'],
        '303' => ['Consultar outro local', 'O servidor retornará esse código quando o solicitante precisar fazer uma solicitação GET separadamente para outro local para obter a resposta'],
        '304' => ['Não modificado', 'A página solicitada não foi modificada desde a última solicitação'],
        '305' => ['Utilizar proxy', 'O solicitante poderá acessar a página solicitada utilizando um proxy'],
        '307' => ['Redirecionamento temporário', 'O servidor está respondendo à solicitação de uma página de uma localidade diferente, mas o solicitante deve continuar a usar o local original para solicitações futuras'],
        '400' => ['Solicitação inválida', 'O servidor não entendeu a sintaxe da solicitação'],
        '401' => ['Não autorizado', 'A solicitação requer autenticação'],
        '403' => ['Proibido', 'O servidor está recusando a solicitação'],
        '404' => ['Não encontrado', 'O servidor não encontrou a página solicitada'],
        '405' => ['Método não permitido', 'O método especificado na solicitação não é permitido'],
        '406' => ['Não aceitável', 'A página solicitada não pode responder com as características de conteúdo solicitadas'],
        '407' => ['Autenticação de proxy necessária', 'Esse código de status é semelhante ao 401 (não autorizado), mas especifica que o solicitante deve autenticar usando uma proxy'],
        '408' => ['Tempo limite da solicitação', 'O servidor atingiu o tempo limite ao aguardar a solicitação'],
        '409' => ['Conflito', 'O servidor encontrou um conflito ao cumprir a solicitação'],
        '410' => ['Desaparecido', 'O servidor retornará essa resposta quando o recurso solicitado tiver sido removido permanentemente'],
        '411' => ['Comprimento necessário', 'O servidor não aceitará a solicitação sem um campo de cabeçalho “Comprimento-do-Conteúdo” válido'],
        '412' => ['Falha na pré-condição', 'O servidor não cumpre uma das pré-condições que o solicitante coloca na solicitação'],
        '413' => ['Entidade de solicitação muito grande', 'O servidor não pode processar a solicitação porque ela é muito grande para a capacidade do servidor'],
        '414' => ['O URI solicitado é muito longo', 'O URI solicitado (geralmente um URL) é muito longo para ser processado pelo servidor'],
        '415' => ['Tipo de mídia incompatível', 'A solicitação está em um formato não compatível com a página solicitada'],
        '416' => ['Faixa solicitada insatisfatória', 'O servidor retorna esse código de status se a solicitação for para uma faixa não disponível para a página'],
        '417' => ['Falha na expectativa', 'O servidor não pode cumprir os requisitos do campo “Expectativa” do cabeçalho da solicitação'],
        '500' => ['Erro interno do servidor', 'O servidor encontrou um erro e não pode completar a solicitação'],
        '501' => ['Não implementado', 'O servidor não tem a funcionalidade para atender à solicitação'],
        '502' => ['Gateway inválido', 'O servidor estava operando como gateway ou proxy e recebeu uma resposta inválida do servidor superior'],
        '503' => ['Serviço indisponível', 'O servidor está indisponível no momento (por sobrecarga ou inatividade para manutenção)'],
        '504' => ['Tempo limite do gateway', 'O servidor estava operando como gateway ou proxy e não recebeu uma solicitação do servidor superior a tempo'],
        '505' => ['Versão HTTP incompatível', 'O servidor não é compatível com a versão do protocolo HTTP usada na solicitação']
    )
];
